[package]
name = "dice"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec={version= "^1.7", features=["union", "const_generics"]}
log = "^0.4"